import type { SitePar } from "./types";

export const DEFAULT_PARS: Record<string, SitePar & { packSize: number }> = {
  "Airheads Bites": { reorderPoint: 9, target: 27, packSize: 18 },
  "Assorted Nuts": { reorderPoint: 12, target: 36, packSize: 24 },
  Butterfinger: { reorderPoint: 18, target: 54, packSize: 36 },
  Chips: { reorderPoint: 15, target: 45, packSize: 30 },
  "Clif Bar": { reorderPoint: 24, target: 72, packSize: 12 },
  Coke: { reorderPoint: 12, target: 36, packSize: 24 },
  "Creme Soda": { reorderPoint: 6, target: 18, packSize: 12 },
  "Diet Coke": { reorderPoint: 12, target: 36, packSize: 24 },
  "Dr Pepper": { reorderPoint: 12, target: 36, packSize: 24 },
  "Gatorade Large": { reorderPoint: 15, target: 45, packSize: 1 },
  "Gatorade Small": { reorderPoint: 48, target: 96, packSize: 24 },
  "Granola Bar": { reorderPoint: 12, target: 60, packSize: 48 },
  "Grape Soda": { reorderPoint: 6, target: 18, packSize: 12 },
  "Kit Kat": { reorderPoint: 18, target: 54, packSize: 36 },
  "Kiwi Strawberry Soda": { reorderPoint: 6, target: 18, packSize: 12 },
  "M&M's": { reorderPoint: 12, target: 60, packSize: 48 },
  "Mountain Rush (Dew)": { reorderPoint: 6, target: 18, packSize: 12 },
  "Orange Soda": { reorderPoint: 6, target: 18, packSize: 12 },
  "Peanut M&M's": { reorderPoint: 12, target: 60, packSize: 48 },
  Popcorn: { reorderPoint: 12, target: 40, packSize: 28 },
  "Protein Shake": { reorderPoint: 12, target: 36, packSize: 12 },
  "Reese's": { reorderPoint: 18, target: 54, packSize: 36 },
  "Root Beer": { reorderPoint: 6, target: 18, packSize: 12 },
  Skittles: { reorderPoint: 12, target: 48, packSize: 36 },
  Snickers: { reorderPoint: 12, target: 60, packSize: 48 },
  "Sour Patch Kids": { reorderPoint: 12, target: 60, packSize: 48 },
  "Sour Punch Straws": { reorderPoint: 6, target: 18, packSize: 24 },
  Sprite: { reorderPoint: 6, target: 18, packSize: 12 },
  "Tiki Punch": { reorderPoint: 6, target: 18, packSize: 12 },
  "Trail Mix": { reorderPoint: 6, target: 30, packSize: 24 },
  Twix: { reorderPoint: 12, target: 48, packSize: 36 },
  "Water Large": { reorderPoint: 30, target: 60, packSize: 15 },
  "Water Small": { reorderPoint: 70, target: 105, packSize: 35 },
};

export const INSTACART_QUERIES: Record<string, string> = {
  "Airheads Bites": "AirHeads Fruit Bites 2 oz \u2022 18 x 2 oz",
  "Assorted Nuts": "First Street Snack Nuts, Roasted & Salted, Assorted, Snack Packs 1.6 oz \u2022 24 x 1.6 oz",
  "Barebells Bar": "Barebells protein bar",
  Butterfinger: "Butterfinger Candy Bars 36 each \u2022 $1.35 each",
  Chips: "Frito Lay Snacks, Variety Mix, Variety Packs 51.5 oz \u2022 $0.43/oz",
  "Clif Bar": "CLIF BAR Energy Bars, Non-Gmo, Plant Based Protein Bars 28.8 oz 2.4 oz \u2022 12 x 2.4 oz",
  Coke: "Coca-Cola Soda 12 fl oz \u2022 24 x 12 fl oz",
  "Creme Soda": "Shasta Soda, Caffeine Free, Creme 12 fl oz \u2022 12 x 12 fl oz",
  "Diet Coke": "Diet Coke Soda Cans 12 fl oz \u2022 24 x 12 fl oz",
  "Dr Pepper": "Dr Pepper Soda, 12 Pack 12 oz \u2022 12 x 12 oz",
  "Gatorade Large": "Gatorade 28 fl oz",
  "Gatorade Small": "Gatorade 20 fl oz \u2022 24 x 20 fl oz",
  "Granola Bar": "Nature Valley Granola Bars 48 ct \u2022 $0.29/oz",
  "Grape Soda": "Shasta Soda, Caffeine Free, Grape 12 fl oz \u2022 12 x 12 fl oz",
  "Kit Kat": "KIT KAT\u00ae Milk Chocolate Wafer Candy Bars, 1.5 oz (36 Count) 1.5 oz \u2022 36 x 1.5 oz",
  "Kiwi Strawberry Soda": "Shasta Soda, Caffeine Free, Kiwi Strawberry 12 fl oz \u2022 12 x 12 fl oz",
  "LMNT Packet": "LMNT electrolyte packets",
  "LMNT Sparkling": "LMNT sparkling",
  "M&M's": "M&M's Milk Chocolate Candy Full Size Bulk Pack 1.69 oz \u2022 48 x 1.69 oz",
  "Mountain Rush (Dew)": "Shasta Soda, Mountain Rush 12 fl oz \u2022 12 x 12 fl oz",
  NOCCO: "NOCCO energy drink",
  "Orange Soda": "Shasta Soda, Caffeine Free, + Vitamin C, Orange 12 fl oz \u2022 12 x 12 fl oz",
  "Peanut M&M's": "M&M's Peanut Milk Chocolate Candy Full Size Bulk 1.74 oz \u2022 48 x 1.74 oz",
  "Pickle Bar": "pickle flavored snack bar",
  Popcorn: "SkinnyPop Popcorn Original 28 ct \u2022 $0.59 each",
  "Protein Shake": "MUSCLE MILK Protein Shake, Zero Sugar, Genuine, 12 Pack 11 fl oz \u2022 12 x 11 fl oz",
  "Reese's": "Reese's Milk Chocolate Peanut Butter Cups Candy 1.5 oz \u2022 36 x 1.5 oz",
  "Root Beer": "Shasta Root Beer, Caffeine Free, Draft Style 12 fl oz \u2022 12 x 12 fl oz",
  Skittles: "Skittles Original Fruity Chewy Candy Box 2.17 oz \u2022 36 x 2.17 oz",
  Snickers: "SNICKERS Full Size Bulk Chocolate Candy Bars 1.86 oz \u2022 48 x 1.86 oz",
  "Sour Patch Kids": "SOUR PATCH KIDS Watermelon Soft & Chewy Gummy Candy, Bulk Candy 48 oz 2 oz \u2022 24 x 2 oz",
  "Sour Punch Straws": "Sour Punch Straws, Rainbow Fruit Flavors Sour Chewy Candy 24 ct \u2022 $0.83 each",
  Sprite: "Sprite Lemon Lime Soda Soft Drinks 12 fl oz \u2022 24 x 12 fl oz",
  "Tiki Punch": "Shasta Soda, Caffeine Free, Tiki Punch 12 fl oz \u2022 12 x 12 fl oz",
  "Trail Mix": "First Street Trail Mix, Mountain, Snack Packs 2 oz \u2022 24 x 2 oz",
  Twix: "TWIX Caramel Cookie Chocolate Candy Bars Bulk Pack 36 ct \u2022 $0.73/oz",
  "Water Large": "Crystal Geyser Natural Alpine Spring Water 33.8 fl oz \u2022 15 x 33.8 fl oz",
  "Water Small": "Crystal Geyser Alpine Spring Water, Natural 16.9 fl oz \u2022 35 x 16.9 fl oz",
};

export const seedExportedOn = "2026-09-17";

