import type { SitePar } from "./types";

export const DEFAULT_PARS: Record<string, SitePar & { packSize: number }> = {
  "Water Small": { reorderPoint: 48, target: 96, packSize: 24 },
  "Water Large": { reorderPoint: 24, target: 48, packSize: 12 },
  Coke: { reorderPoint: 24, target: 48, packSize: 12 },
  "Diet Coke": { reorderPoint: 18, target: 36, packSize: 12 },
  Sprite: { reorderPoint: 18, target: 36, packSize: 12 },
  "Dr Pepper": { reorderPoint: 12, target: 24, packSize: 12 },
  "Creme Soda": { reorderPoint: 12, target: 24, packSize: 12 },
  "Grape Soda": { reorderPoint: 12, target: 24, packSize: 12 },
  "Kiwi Strawberry Soda": { reorderPoint: 12, target: 24, packSize: 12 },
  "Orange Soda": { reorderPoint: 12, target: 24, packSize: 12 },
  "Root Beer": { reorderPoint: 12, target: 24, packSize: 12 },
  "Mountain Rush (Dew)": { reorderPoint: 12, target: 24, packSize: 12 },
  "Tiki Punch": { reorderPoint: 12, target: 24, packSize: 12 },
  "Gatorade Small": { reorderPoint: 24, target: 48, packSize: 12 },
  "Gatorade Large": { reorderPoint: 12, target: 24, packSize: 6 },
  "LMNT Packet": { reorderPoint: 60, target: 120, packSize: 30 },
  "LMNT Sparkling": { reorderPoint: 12, target: 24, packSize: 12 },
  NOCCO: { reorderPoint: 36, target: 72, packSize: 12 },
  "Protein Shake": { reorderPoint: 18, target: 36, packSize: 12 },
  "Airheads Bites": { reorderPoint: 12, target: 24, packSize: 12 },
  "Assorted Nuts": { reorderPoint: 8, target: 16, packSize: 8 },
  "Barebells Bar": { reorderPoint: 12, target: 24, packSize: 12 },
  Butterfinger: { reorderPoint: 12, target: 24, packSize: 12 },
  Chips: { reorderPoint: 24, target: 48, packSize: 12 },
  "Clif Bar": { reorderPoint: 24, target: 48, packSize: 12 },
  "Granola Bar": { reorderPoint: 24, target: 48, packSize: 12 },
  "Kit Kat": { reorderPoint: 12, target: 24, packSize: 12 },
  "M&M's": { reorderPoint: 12, target: 24, packSize: 12 },
  "Peanut M&M's": { reorderPoint: 12, target: 24, packSize: 12 },
  "Pickle Bar": { reorderPoint: 8, target: 16, packSize: 8 },
  Popcorn: { reorderPoint: 12, target: 24, packSize: 12 },
  "Reese's": { reorderPoint: 12, target: 24, packSize: 12 },
  Skittles: { reorderPoint: 12, target: 24, packSize: 12 },
  Snickers: { reorderPoint: 12, target: 24, packSize: 12 },
  "Sour Patch Kids": { reorderPoint: 12, target: 24, packSize: 12 },
  "Sour Punch Straws": { reorderPoint: 12, target: 24, packSize: 12 },
  "Trail Mix": { reorderPoint: 8, target: 16, packSize: 8 },
  Twix: { reorderPoint: 12, target: 24, packSize: 12 },
};

export const INSTACART_QUERIES: Record<string, string> = {
  "Airheads Bites": "Airheads Bites candy",
  "Assorted Nuts": "mixed nuts roasted salted",
  "Barebells Bar": "Barebells protein bar",
  Butterfinger: "Butterfinger candy bar",
  Chips: "potato chips variety",
  "Clif Bar": "Clif Bar",
  Coke: "Coca-Cola classic cans",
  "Creme Soda": "creme soda cans",
  "Diet Coke": "Diet Coke cans",
  "Dr Pepper": "Dr Pepper cans",
  "Gatorade Large": "Gatorade 28 oz",
  "Gatorade Small": "Gatorade 20 oz",
  "Granola Bar": "granola bars",
  "Grape Soda": "grape soda cans",
  "Kit Kat": "Kit Kat candy bar",
  "Kiwi Strawberry Soda": "kiwi strawberry soda",
  "LMNT Packet": "LMNT electrolyte packets",
  "LMNT Sparkling": "LMNT sparkling",
  "M&M's": "M&M's milk chocolate",
  "Mountain Rush (Dew)": "Mountain Dew cans",
  NOCCO: "NOCCO energy drink",
  "Orange Soda": "orange soda cans",
  "Peanut M&M's": "Peanut M&M's",
  "Pickle Bar": "pickle flavored snack bar",
  Popcorn: "bagged popcorn",
  "Protein Shake": "ready to drink protein shake",
  "Reese's": "Reese's Peanut Butter Cups",
  "Root Beer": "root beer cans",
  Skittles: "Skittles candy",
  Snickers: "Snickers candy bar",
  "Sour Patch Kids": "Sour Patch Kids",
  "Sour Punch Straws": "Sour Punch Straws",
  Sprite: "Sprite cans",
  "Tiki Punch": "fruit punch soda cans",
  "Trail Mix": "trail mix",
  Twix: "Twix candy bar",
  "Water Large": "bottled water 1 liter",
  "Water Small": "bottled water 16.9 oz case",
};

export const seedExportedOn = "2026-09-17";
